package com.qf.oa.entity;

import java.util.Date;

public class SysMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_ID
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_PARENT_ID
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private Long menuParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_NAME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_TYPE
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private Short menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_PATH
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private String menuPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.MENU_DESC
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.IS_PUBLISH
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private Boolean isPublish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.CREATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_ID
     *
     * @return the value of sys_menu.MENU_ID
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_ID
     *
     * @param menuId the value for sys_menu.MENU_ID
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_PARENT_ID
     *
     * @return the value of sys_menu.MENU_PARENT_ID
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public Long getMenuParentId() {
        return menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_PARENT_ID
     *
     * @param menuParentId the value for sys_menu.MENU_PARENT_ID
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setMenuParentId(Long menuParentId) {
        this.menuParentId = menuParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_NAME
     *
     * @return the value of sys_menu.MENU_NAME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_NAME
     *
     * @param menuName the value for sys_menu.MENU_NAME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_TYPE
     *
     * @return the value of sys_menu.MENU_TYPE
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public Short getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_TYPE
     *
     * @param menuType the value for sys_menu.MENU_TYPE
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setMenuType(Short menuType) {
        this.menuType = menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_PATH
     *
     * @return the value of sys_menu.MENU_PATH
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public String getMenuPath() {
        return menuPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_PATH
     *
     * @param menuPath the value for sys_menu.MENU_PATH
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setMenuPath(String menuPath) {
        this.menuPath = menuPath == null ? null : menuPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.MENU_DESC
     *
     * @return the value of sys_menu.MENU_DESC
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.MENU_DESC
     *
     * @param menuDesc the value for sys_menu.MENU_DESC
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc == null ? null : menuDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.IS_PUBLISH
     *
     * @return the value of sys_menu.IS_PUBLISH
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public Boolean getIsPublish() {
        return isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.IS_PUBLISH
     *
     * @param isPublish the value for sys_menu.IS_PUBLISH
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setIsPublish(Boolean isPublish) {
        this.isPublish = isPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.CREATE_TIME
     *
     * @return the value of sys_menu.CREATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.CREATE_TIME
     *
     * @param createTime the value for sys_menu.CREATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.UPDATE_TIME
     *
     * @return the value of sys_menu.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.UPDATE_TIME
     *
     * @param updateTime the value for sys_menu.UPDATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:47:08 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}