package com.qf.oa.entity;

import java.util.Date;

public class SysRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_ID
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_NAME
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_DESC
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.FLAG
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    private Boolean flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CREATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_ID
     *
     * @return the value of sys_role.ROLE_ID
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_ID
     *
     * @param roleId the value for sys_role.ROLE_ID
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_NAME
     *
     * @return the value of sys_role.ROLE_NAME
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_NAME
     *
     * @param roleName the value for sys_role.ROLE_NAME
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_DESC
     *
     * @return the value of sys_role.ROLE_DESC
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_DESC
     *
     * @param roleDesc the value for sys_role.ROLE_DESC
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.FLAG
     *
     * @return the value of sys_role.FLAG
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public Boolean getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.FLAG
     *
     * @param flag the value for sys_role.FLAG
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CREATE_TIME
     *
     * @return the value of sys_role.CREATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CREATE_TIME
     *
     * @param createTime the value for sys_role.CREATE_TIME
     *
     * @mbggenerated Thu Feb 14 01:48:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}